-- Script to create tables for the Telco Project.
-- Constraints and indexes are included to ensure 3NF and fast querying.

CREATE TABLE TARIFFS (
    TARIFF_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL UNIQUE,
    MONTHLY_FEE NUMBER NOT NULL,
    DATA_LIMIT NUMBER NOT NULL,
    MINUTE_LIMIT NUMBER NOT NULL,
    SMS_LIMIT NUMBER NOT NULL
);

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    CITY VARCHAR2(100) NOT NULL,
    SIGNUP_DATE DATE NOT NULL,
    TARIFF_ID NUMBER NOT NULL,
    CONSTRAINT FK_CUST_TARIFF FOREIGN KEY (TARIFF_ID) REFERENCES TARIFFS(TARIFF_ID)
);

CREATE INDEX IDX_CUST_CITY ON CUSTOMERS(CITY);
CREATE INDEX IDX_CUST_SIGNUP_DATE ON CUSTOMERS(SIGNUP_DATE);
CREATE INDEX IDX_CUST_TARIFF ON CUSTOMERS(TARIFF_ID);

CREATE TABLE MONTHLY_STATS (
    ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER NOT NULL,
    DATA_USAGE NUMBER NOT NULL,
    MINUTE_USAGE NUMBER NOT NULL,
    SMS_USAGE NUMBER NOT NULL,
    PAYMENT_STATUS VARCHAR2(20) NOT NULL,
    CONSTRAINT FK_STATS_CUST FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

CREATE INDEX IDX_STATS_CUST ON MONTHLY_STATS(CUSTOMER_ID);
CREATE INDEX IDX_STATS_PAYMENT ON MONTHLY_STATS(PAYMENT_STATUS);
