OPTIONS (SKIP=1)
LOAD DATA
INFILE '/tmp/CUSTOMERS.csv'
APPEND
INTO TABLE CUSTOMERS
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  CUSTOMER_ID,
  NAME,
  CITY,
  SIGNUP_DATE DATE "DD/MM/YYYY",
  TARIFF_ID
)
