OPTIONS (SKIP=1)
LOAD DATA
INFILE '/tmp/MONTHLY_STATS.csv'
APPEND
INTO TABLE MONTHLY_STATS
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID,
  CUSTOMER_ID,
  DATA_USAGE,
  MINUTE_USAGE,
  SMS_USAGE,
  PAYMENT_STATUS
)
