OPTIONS (SKIP=1)
LOAD DATA
INFILE '/tmp/TARIFFS.csv'
APPEND
INTO TABLE TARIFFS
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  TARIFF_ID,
  NAME,
  MONTHLY_FEE,
  DATA_LIMIT,
  MINUTE_LIMIT,
  SMS_LIMIT
)
